//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineStation
    {
        public int LineStations_id { get; set; }
        public Nullable<int> Line_id { get; set; }
        public Nullable<int> Station_id { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Station Station { get; set; }
    }
}
