//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Wagon_id { get; set; }
        public Nullable<System.DateTime> DayAndTime { get; set; }
        public Nullable<int> DepartureStation_id { get; set; }
        public Nullable<int> ArrivalStation_id { get; set; }
        public Nullable<int> NumberOfSeat { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual User User { get; set; }
        public virtual Wagon Wagon { get; set; }
    }
}
