//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wagon()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Wagon_id { get; set; }
        public Nullable<int> Train_id { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual Train Train { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
